version: '20.10.12,'

services:
  database:
    image: postgres
    container_name: notes
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
